name: Generate TEI body

on: 
  workflow_dispatch:

jobs:
  build_pages:
    name: Generate TEI body
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # # added or changed files to the repository.
      contents: write
    env:
      ANT_OPTS: -Xmx5g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Generate TEI text & facsimile
      run: ./generate_body.py
    - name: Amend picture paths
      run: ./amend_pics_paths.sh || true
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Export and Transformation done
