name: Download and transform

on: 
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '05 00 * * *'

jobs:
  build_pages:
    name: Download METS files from Transkribus and convert them to TEIs
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # # added or changed files to the repository.
      contents: write
    env:
      ANT_OPTS: -Xmx5g
      TR_USER: ${{ secrets.TR_USER }}
      TR_PW: ${{ secrets.TR_PW }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BASEROW_USER: ${{ secrets.BASEROW_USER }}
      BASEROW_PW: ${{ secrets.BASEROW_PW }}
      BASEROW_READ_TOKEN: ${{ secrets.BASEROW_READ_TOKEN }}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Install Python Packages
      run: pip install -U -r requirements.txt
    - name: Delete old METS
      run: rm -rf mets/*
    - name: Delete old files
      run: rm -f data/editions/*
    - name: Download
      run: python download.py
    - name: Delete non-included files
      run: rm -f mets/216937/{2926205,1523134,2914584,2926205,3374447,3374448,3374547,3376967,377127,3377287,3385787,3406471,3377127}* || true
    - name: Transform
      run: python transform.py
    - name: Amend duplicates
      run: ./amend_duplicate.py || true
    - name: Rename files
      run: ./renamefiles.py
    - name: Regenerate headers
      run: ./generate_headers.py
    - name: Generate TEI text & facsimile
      run: ./generate_body.py
    - name: Ammend picture paths
      run: ./amend_pics_paths.sh
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Export and Transformation done
