name: Just download

on: 
  workflow_dispatch:

jobs:
  build_pages:
    name: Download METS files from Transkribus
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # # added or changed files to the repository.
      contents: write
    env:
      ANT_OPTS: -Xmx5g
      TR_USER: ${{ secrets.TR_USER }}
      TR_PW: ${{ secrets.TR_PW }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Download
      run: ./pyscripts/download.py
    - name: Delete non included files
      run: rm -f data/mets/216937/{2926205,1523134,2914584,2926205,3374447,3374448,3374547,3376967,377127,3377287,3385787,3406471,3377127}* || true
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Export and Transformation done
