name: Regenerate headers

on: 
  workflow_dispatch:

jobs:
  build_pages:
    name: Regenerates headers for the XML-TEI files using the table as source
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # # added or changed files to the repository.
      contents: write
    env:
      ANT_OPTS: -Xmx5g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
    - name: Install Python Packages
      run: pip install -r requirements.txt
    - name: Delete old files
      run: rm -rf ./tei_headers/*
    - name: Regenerate headers
      run: ./generate_headers.py
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Export and Transformation done
